### ISSUE TITLE
it stopped working!

### ISSUE THREAD

**Issue by leandrop20** [myflashlab/AS3-youtube-parser-video-link#4]
[IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #2032: Stream Error. URL: https://www.youtube.com/get_video_info?&video_id=VIDEO_ID&asv=3&el=detailpage&hl=en_US" errorID=2032]

changing method to GET, returned, but no working yet.

could you help me? thanks!

**Comment by tonystech** [comment]
Same issue here. Randomly stopped working. Getting, "Error: could not connect to server!" in my as3 console.

**Comment by jam65st** [comment]
Same Issue, YouTube change **POST** to **GET** and change the received **loader.data** (_onRawDataReceived_ event handler); 

The most of contents are **now availables** in: 
<br>__videoFormats_  **->**  _videoVars.player_response_
<br>__videoTitleOrg_  **->**  _videoVars.videoDetails.title_
<br>__thumbLink_ **->** _videoVars.videoDetails.thumbnail.thumbnails[ **n** ].url_ (where **n** is the number of desired thumb in the received array)

In the **_videoFormats[ x ].url** is not included the var **ipbits** in the content.

I will continue working on this issue because I have my app down.

---
**Note:** in **_parse_** method you must need include your **API_KEY** in the URL (_vidInfo_) as variable:
`var vidInfo:String = 'https://www.youtube.com/get_video_info?video_id=' + _videoId + '&asv=3&el=detailpage&hl=en_US&key=[YOUR API KEY];`

**Comment by dgurney75** [comment]
What API_KEY are you referring to?

**Comment by dgurney75** [comment]
Has anyone figured out how to fix this?

**Comment by myflashlab** [comment]
Updated the library and it now correctly grabs the video URLs. The only change you have to do on your side is to pick the video you want like this:

```actionscript
var chosenVideo:String;
for (var i:int = 0; i < _ytParser.videoFormats.length; i++) 
{
	var currVideoData:Object = _ytParser.videoFormats[i];
	if (currVideoData.mimeType.indexOf(VideoType.VIDEO_MP4) > -1 && currVideoData.quality == VideoQuality.MEDIUM)
	{
		chosenVideo = currVideoData.url;
		break;
	}
}
```
